### ISSUE TITLE
[Feature]: Is there an unpacked and compressed version of the code?

### ISSUE THREAD

**Issue by laochake** [prostgles/ui#2]
### Requested Behavior

I need to change something of the ui

### How to achieve this now

 Is there an unpacked and compressed version of the code?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prostgles** [comment]
The current UI codebase is undergoing major refactoring to make it more developer friendly and to allow reusing components in other projects.
In the near future there will be an unpacked UI code base and until then you could try sharing what feature/change you need in case it's a something we're already working on or easy to add.

**Comment by laochake** [comment]
> 

Thank you very much. I am more curious and intelligent to complete this piece haha

**Comment by laochake** [comment]
> The current UI codebase is undergoing major refactoring to make it more developer friendly and to allow reusing components in other projects. In the near future there will be an unpacked UI code base and until then you could try sharing what feature/change you need in case it's a something we're already working on or easy to add.



> The current UI codebase is undergoing major refactoring to make it more developer friendly and to allow reusing components in other projects. In the near future there will be an unpacked UI code base and until then you could try sharing what feature/change you need in case it's a something we're already working on or easy to add.

Thank you very much~  more curious intelligent completion hah
