### ISSUE TITLE
[Bug]: Prostgless used a random database to store it's own stuff

### ISSUE THREAD

**Issue by ruXlab** [prostgles/ui#27]
### What happened?

**Affected version:** 7eead76

**Bug:**
The first launch of the prostgless against the live database resulted in unexpected behaviour. Without explicit user permission the Prostgless created number of internal tables in the first(alphabetically sorted) database available.

**Expected behaviour:**
Either require user to provide database for the metadata or attempt to create a dedicated database for metadata

### What OS are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Chrome

**Comment by prostgles** [comment]
README.md was updated to reflect this
