### ISSUE TITLE
[Feature]: Apple Intel support for Desktop app

### ISSUE THREAD

**Issue by aleclarson** [prostgles/ui#55]
### Requested Behavior

When I install 2.0.27-alpha.dmg, it doesn't let me run the application.

<img width="275" alt="Screenshot 2024-11-08 at 12 49 51" src="https://github.com/user-attachments/assets/1f6b47d4-8036-47bf-b958-134968491271">

- macOS Sonoma 14.4.1

### How to achieve this now

Provide an Intel-compatible build

**Comment by prostgles** [comment]
Architecture changed to "universal". Please confirm if this fixes your issue. 
Build and installation files:  
https://github.com/prostgles/ui/actions/runs/11748100590

**Comment by aleclarson** [comment]
Thanks!
