### ISSUE TITLE
[Bug]: Onboarding inconvinience - lost workspace after creating the first user

### ISSUE THREAD

**Issue by ruXlab** [prostgles/ui#61]
### What happened?

I've been using prostgles for some time now in the passwordless mode and so far it's been great experience!

However, I wasn't able to open the webapp from another browser because prostgles insisted on creating a dedicated user. Once user is created the 'passwordless admin' is blocked and it doesn't seem to be possible to reactivate it. Unfortunately there is no migration in place so I've lost all my SQL sheets in the workspace - it's quite frustrating.

Expected behaviour:
1) User should be informed that they'll lose access to the current workspace so they can do backups
2) Offer optional migration of the workspace when the first user is being created.

### Which product are you seeing the problem on?

UI

### What OS are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Chrome

**Comment by prostgles** [comment]
We have updated the logic to ensure the old user data is available to the new admin user.

To fix your current issue can you please adapt and execute the SQL script below in the "Prostgles UI state database". It should allow you to access old admin user workspaces through your new user

sql```
/** Reassign user data */
DO $$ 
  DECLARE old_admin_id UUID := (SELECT id FROM users WHERE passwordless_admin = TRUE);
   new_admin_id UUID := (SELECT id FROM users WHERE username = 'your_new_admin_username');
BEGIN

  UPDATE workspaces
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id;

  UPDATE windows
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id;

  UPDATE links
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id;

END $$;
```

**Comment by ruXlab** [comment]
Thanks for the quick response!

Unfortunately this query fails:
```lua
duplicate key value violates unique constraint "unique_name_per_user_perCon" 
 Key (connection_id, user_id, name)=(badd46aa-8b35-40fa-913f-e6d4129b6318, 61971eed-f18b-472e-8912-593d99607192, default) already exists. 
 where: SQL statement "UPDATE workspaces
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id"
PL/pgSQL function inline_code_block line 6 at SQL statement
```

**Comment by prostgles** [comment]
This is happening because you have workspaces with the same name on the new account. This query should fix the problem by appending  " old"  to any clashing imported workspace names

```sql
/** Reassign user data */
DO $$ 
  DECLARE old_admin_id UUID := (SELECT id FROM users WHERE passwordless_admin = TRUE);
   new_admin_id UUID := (SELECT id FROM users WHERE username = 'your_new_admin_username');
BEGIN

  /** Append ' old' to clashing workspace names first */
  UPDATE workspaces old_wsp
  SET name = name || ' old'
  WHERE user_id = old_admin_id
  AND EXISTS (
    SELECT * 
    FROM workspaces existing_wsp
    WHERE user_id = new_admin_id
    AND old_wsp.connection_id = existing_wsp.connection_id
    AND old_wsp.name = existing_wsp.name
  );

  UPDATE workspaces
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id;

  UPDATE windows
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id;

  UPDATE links
  SET user_id = new_admin_id
  WHERE user_id = old_admin_id;

END $$;
```
